version: "3.7"
services:

  mysql_db:
    platform: linux/x86_64
    image: mysql:latest
    restart: always
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    container_name: mysql-test-7
    ports:
      - "23306:3306"
    environment:
      - MYSQL_DATABASE=golf
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul

  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"

    volumes:
      - /Users/nogyeongtae/Shared/data/golf-mysql:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog
    ports:
      - "8083:8083"