spring:
  config:
    activate:
      on-profile: dev
  redis:
    lettuce:
      pool:
        max-active: 200
        max-idle: 10
        min-idle: 2
    port: 6379
    host: redis

  datasource:
    url: jdbc:mysql://mysql_blog:3306/newblog
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: golf
    password: 1234
    hikari:
      maximum-pool-size: 100

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: validate

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  accessToken-validity-in-seconds: 3600 # 1시간
  refreshToken-validity-in-seconds: 18000 # 5시간
